@startuml



folder "Portal" [[../computational/portal/index.html]] {
}
folder "Brockmann Consult Processing Centre" [[../computational/bc-pc/index.html]] {
}
folder "IT4Innovations Processing Centre" [[../computational/it4i-pc/index.html]] {
}
folder "DLR Processing Centre" [[../computational/dlr-pc/index.html]] {
}

@enduml
