@startuml
package "Terradue" <<Frame>> {
  class "Terradue::Authentication::Umsso" as namespace_terradue_1_1_authentication_1_1_umsso
  class "Terradue::GeoJson" as namespace_terradue_1_1_geo_json
  class "Terradue::Github" as namespace_terradue_1_1_github
  class "Terradue::Metadata::EarthObservation" as namespace_terradue_1_1_metadata_1_1_earth_observation
  class "Terradue::News" as namespace_terradue_1_1_news
  class "Terradue::OpenSearch::GeoJson" as namespace_terradue_1_1_open_search_1_1_geo_json
  class "Terradue::OpenSearch::SciHub" as namespace_terradue_1_1_open_search_1_1_sci_hub
  class "Terradue::OpenSearch::Kml" as namespace_terradue_1_1_open_search_1_1_kml
  class "Terradue::OpenSearch::RdfEO" as namespace_terradue_1_1_open_search_1_1_rdf_e_o
  class "Terradue::OpenSearch" as namespace_terradue_1_1_open_search
  class "Terradue::Portal" as namespace_terradue_1_1_portal
  class "Terradue::ServiceModel::Ogc::OwsContext" as namespace_terradue_1_1_service_model_1_1_ogc_1_1_ows_context
  class "Terradue::ServiceModel::Syndication" as namespace_terradue_1_1_service_model_1_1_syndication
  class "Terradue::Tep" as namespace_terradue_1_1_tep
  class "Terradue::WebService::Model" as namespace_terradue_1_1_web_service_1_1_model
  
}

   !include ../../source/namespaces/namespace_terradue_1_1_authentication_1_1_umsso.iuml
   !include ../../source/namespaces/namespace_terradue_1_1_geo_json.iuml
   
   !include ../../source/namespaces/namespace_terradue_1_1_github.iuml
   !include ../../source/namespaces/namespace_terradue_1_1_metadata_1_1_earth_observation.iuml
   !include ../../source/namespaces/namespace_terradue_1_1_service_model_1_1_ogc_1_1_ows_context.iuml
   !include ../../source/namespaces/namespace_terradue_1_1_service_model_1_1_syndication.iuml
   !include ../../source/namespaces/namespace_terradue_1_1_news.iuml
   !include ../../source/namespaces/namespace_terradue_1_1_open_search_1_1_kml.iuml
   !include ../../source/namespaces/namespace_terradue_1_1_open_search_1_1_sci_hub.iuml
   !include ../../source/namespaces/namespace_terradue_1_1_open_search_1_1_geo_json.iuml
   !include ../../source/namespaces/namespace_terradue_1_1_open_search_1_1_rdf_e_o.iuml
   !include ../../source/namespaces/namespace_terradue_1_1_open_search.iuml
   !include ../../source/namespaces/namespace_terradue_1_1_portal.iuml
   !include ../../source/namespaces/namespace_terradue_1_1_tep.iuml
   !include ../../source/namespaces/namespace_terradue_1_1_web_service_1_1_model.iuml

@enduml
