@startuml
[group___auth___umsso]  --  [group___authentication] : implements
[group___authentication]  ..>  [group___persistence] : []
[group___authorisation]  ..>  [group___persistence] : []
[group___context]  ..>  [group___persistence] : []
[group___context]  ..>  [group___authorisation] : []
[group___context]  ..>  [group___authentication] : []
[group___data_package]  ..>  [group___series] : uses
[group___data_package]  ..>  [group___open_searchable] : implements
[group___github_profile]  ..>  [group___persistence] : calls
[group___github_profile]  ..>  [group___github_client] : uses
[group___open_search_engine]  --  [group___open_searchable] : process
[group___open_search_engine]  ..>  [group___syndication] : uses
[group___persistence]  --  [group___s_q_l_connector] : connects
[group___series]  ..>  [group___persistence] : []
[group___series]  ..>  [group___authorisation] : []
[group___service]  ..>  [group___persistence] : []
[group___service]  ..>  [group___authorisation] : []
[group___tep_user]  ..>  [group___context] : uses
[group___tep_user]  ..>  [group___github_profile] : uses
[group___tep_user]  ..>  [group___authentication] : calls
[group___tep_user]  ..>  [group___github_client] : calls
[group___web_context]  ..>  [group___context] : []
[group___wps_provider]  ..>  [group___o_w_s_context] : exports
[group___wps_provider]  --  [group___open_searchable] : implements
[group___wps_provider]  --  [group___w_p_s] : implements
[group___wps_service]  ..>  [group___service] : extends
[group___wps_service]  ..>  [group___o_w_s_context] : exports
[group___wps_service]  --  [group___open_searchable] : implements
@enduml
