@startuml
folder "Tep Modules" [[../groups/group___tep.html]] {
	!include group___tep_accounting.iuml
	!include group___tep_application.iuml
	!include group___tep_community.iuml
	!include group___tep_contents.iuml
	!include group___tep_data.iuml
	!include group___tep_service.iuml
}
@enduml
