@startuml
package "Terradue::Authentication::Umsso" <<Frame>> {
  class "Library" as namespace_terradue_1_1_authentication_1_1_umsso << (L, cyan) >> [[../technology/packages/namespace_terradue_1_1_authentication_1_1_umsso.html]] {
     version : 1.2.3 
     license : incubating
  }
}
@enduml
