@startuml
  class "Terradue::Portal" as namespace_terradue_1_1_portal << (L, #27556C) >> [[../namespaces/namespace_terradue_1_1_portal.html]] {
     version : 2.6.42 
     lang : C#
     license : incubating
     nature : OSS
  }
@enduml
