@startuml
  class "Terradue::Authentication::Umsso" as namespace_terradue_1_1_authentication_1_1_umsso << (L, #27556C) >> [[../namespaces/namespace_terradue_1_1_authentication_1_1_umsso.html]] {
     version : 1.2.3 
     lang : C#
     license : incubating
     nature : OSS
  }
@enduml
