@startuml
  class "Terradue::Github" as namespace_terradue_1_1_github << (L, #27556C) >> [[../namespaces/namespace_terradue_1_1_github.html]] {
     version : 1.0.4 
     lang : C#
     license : incubating
     nature : OSS
  }
@enduml
