@startuml
  class "Terradue::ServiceModel::Ogc::OwsContext" as namespace_terradue_1_1_service_model_1_1_ogc_1_1_ows_context << (L, #27556C) >> [[../namespaces/namespace_terradue_1_1_service_model_1_1_ogc_1_1_ows_context.html]] {
     version : 1.0.6 
     lang : C#
     license : GPLv3
     nature : OSS
  }
@enduml
