@startuml
  class "Apel::Server" as namespace_apel_1_1_server << (S, #86A136) >> [[../namespaces/namespace_apel_1_1_server.html]] {
     version : 1.5.0 
     lang : Python 
     license : Apache-2
     nature : OSS 
  }
@enduml
