@startuml
  class "MySql::Data" as namespace_my_sql_1_1_data << (L, #86A136) >> [[../namespaces/namespace_my_sql_1_1_data.html]] {
     version : 6.9.8 
     lang : C#
     license : GPL-v2
     nature : .Net OSS 
  }
@enduml
