@startuml
  class "Terradue::ServiceModel::Syndication" as namespace_terradue_1_1_service_model_1_1_syndication << (L, #27556C) >> [[../namespaces/namespace_terradue_1_1_service_model_1_1_syndication.html]] {
     version : 1.0.0 
     lang : C#
     license : GPLv3
     nature : OSS
  }
@enduml
