@startuml
  class "Terradue::News" as namespace_terradue_1_1_news << (L, #27556C) >> [[../namespaces/namespace_terradue_1_1_news.html]] {
     version : 1.0.11 
     lang : C#
     license : incubating
     nature : OSS
  }
@enduml
