@startuml
  class "Terradue::WebService::Model" as namespace_terradue_1_1_web_service_1_1_model << (L, #27556C) >> [[../namespaces/namespace_terradue_1_1_web_service_1_1_model.html]] {
     version : 1.1.3 
     lang : C#
     license : incubating
     nature : OSS
  }
@enduml
