@startuml
set namespaceSeparator ::
class Terradue::Cloud::CloudProvider {
[[../information/classes/class_terradue_1_1_cloud_1_1_cloud_provider.html]]
 +AccessPoint:string
 +FindVirtualMachineTemplates()
 +FindVirtualDisks()
 +FindVirtualNetworks()
 +FindAppliances()
 +CreateInstance()
}
@enduml
