@startuml
Feature  --|>  Entity : implements
Group  --|>  Entity : implements
Series  --|>  Entity : implements
Service  --|>  Entity : implements
User  --|>  Entity : implements
WpsProcessOffering  *-- "1" WpsProvider : has
WpsProcessOffering  --|>  Service : implements
OwcCreator  *-- "1" OwcApplication : created on 
OwcCreator  *-- "1" OwcDisplay : displayed on 
OwcOffering  *-- "*" OwcOperation : offers 
OwcOffering  *-- "*" OwcContent : offers 
OwcOperation  *-- "1" OwcContent : is invoked with 
OwcResource  *-- "*" OwcOffering : exposes 
OwsContext  *-- "1" OwcCreator : references 
OwsContext  *-- "*" OwcResource : contains 
Account  *-- "1" UserTep : has
Account  *-- "1" GroupTep : has
Collection  --|>  Series : implements
DataPackage  *-- "1" UserTep : has
DataPackage  *-- "*" Collection : has
GroupTep  *-- "*" UserTep : has
GroupTep  --|>  Group : implements
Rates  *-- "1" Entity : has
RoleTep  --|>  Entity : implements
ThematicApplication  *-- "*" Collection : has
ThematicApplication  *-- "*" WpsProcessOffering : has
ThematicApplication  --|>  Entity : implements
UserTep  *-- "*" GroupTep : has
UserTep  --|>  User : implements
@enduml
