@startuml
set namespaceSeparator ::
class Terradue::Portal::Series {
[[../information/classes/class_terradue_1_1_portal_1_1_series.html]]
 +Description:string
 +CatalogueDescriptionUrl:string
 +GetLocalOpenSearchDescription()
 +FromOpenSearchUrl()
}
@enduml
