@startuml
set namespaceSeparator ::
class Terradue::Cloud::CloudAppliance {
[[../information/classes/class_terradue_1_1_cloud_1_1_cloud_appliance.html]]
 +RemoteId:string
 +Hostname:string
 +Owner:string
 +Cores:int
 +Memory:float
 +State:MachineState
 +Start()
 +Stop()
 +Suspend()
 +Resume()
 +Shutdown()
}
@enduml
