@startuml
class Entity {
[[../classes/class_terradue_1_1_portal_1_1_entity.html]]
 +Id:int
 +Identifier:string
 +Name:string
 +CanCreate:bool
 +CanChange:bool
 +CanDelete:bool
 +Load()
 +Load()
 +Store()
 +StorePrivilegesForUsers()
 +StorePrivilegesForGroups()
 +StoreGlobalPrivileges()
 +RemoveGlobalPrivileges()
 +Delete()
}
@enduml
