@startuml
class Service {
[[../classes/class_terradue_1_1_portal_1_1_service.html]]
 +Description:string
 +Version:string
 +Url:string
 +IconUrl:string
 +Rating:int
 +ClassId:int
 +OnBuildTask:BuildTaskCallbackType
 +GetParameters()
 +CheckParameters()
 +BuildTask()
}
@enduml
