@startuml
set namespaceSeparator ::
class Terradue::ServiceModel::Ogc::OwsModel::OwsContext {
[[../classes/class_terradue_1_1_service_model_1_1_ogc_1_1_ows_model_1_1_ows_context.html]]
 +Title:string
 +Abstract:string
 +UpdateDate:DateTimeOffset
 +Authors:List< string >
 +Publisher:string
 +ContextMetadata:object
}
@enduml
