@startuml
set namespaceSeparator ::
class Terradue::ServiceModel::Ogc::OwsModel::OwcResource {
[[../information/classes/class_terradue_1_1_service_model_1_1_ogc_1_1_ows_model_1_1_owc_resource.html]]
 +Title:string
 +Abstract:string
 +UpdateDate:DateTimeOffset
 +Authors:List< string >
 +Publisher:string
 +GeospatialExtent:object
 +Preview:List< Uri >
 +ContentByRef:List< Uri >
}
@enduml
