@startuml
set namespaceSeparator ::
class Terradue::Portal::Entity {
[[../classes/class_terradue_1_1_portal_1_1_entity.html]]
 +Id:int
 +Identifier:string
 +Name:string
 +Load()
 +Load()
 +Store()
 +StorePrivilegesForUsers()
 +StorePrivilegesForGroups()
 +StoreGlobalPrivileges()
 +RemoveGlobalPrivileges()
 +Delete()
 +GetAllowedAdministratorOperations()
}
@enduml
